services:
  # Инфраструктура: Брокер сообщений
  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - microservices-net
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Инфраструктура: Трассировка
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - microservices-net

  # Инфраструктура: Redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - microservices-net

  # Инфраструктура: Метрики
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"
    networks:
      - microservices-net

  # Инфраструктура: Визуализация метрик
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
    networks:
      - microservices-net

  # CI/CD: Jenkins
  jenkins:
    build: ./jenkins-dockerfile
    user: root
    ports:
      - "8088:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - microservices-net

  # Микросервисы
  reservation-price-service:
    build:
      context: .  # Корень проекта
      dockerfile: reservation-price-service/Dockerfile  # Относительный путь
    ports:
      - "9090:9090" # gRPC порт
      - "9092:9091" # HTTP порт для actuator
    environment:
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
    networks:
      - microservices-net

  price-client-service:
    build:
      context: .  # Корень проекта
      dockerfile: price-client-service/Dockerfile  # Относительный путь
    ports:
      - "8084:8084"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - GRPC_CLIENT_RESERVATION_PRICE_SERVICE_ADDRESS=static://reservation-price-service:9090
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
    depends_on:
      rabbitmq:
        condition: service_healthy
      reservation-price-service:
        condition: service_started
    networks:
      - microservices-net

  notification-service:
    build:
      context: .  # Корень проекта
      dockerfile: notification-service/notification-service/Dockerfile  # Относительный путь
    ports:
      - "8083:8083"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - SERVER_PORT=8083
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - microservices-net

  audit-service:
    build:
      context: .  # Корень проекта
      dockerfile: audit-service/audit-service/Dockerfile  # Относительный путь
    ports:
      - "8082:8082"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - SERVER_PORT=8082
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - microservices-net

  demo-rest:
    build:
      context: .  # Корень проекта
      dockerfile: demo/Dockerfile  # Относительный путь
    ports:
      - "8081:8080"  # Изменен внешний порт, чтобы не конфликтовать с Jenkins
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/restaurant_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=290404
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      # Указываем адрес gRPC сервиса внутри сети Docker
      - GRPC_CLIENT_RESERVATION_PRICE_SERVICE_ADDRESS=static://reservation-price-service:9090
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
      reservation-price-service:
        condition: service_started
      price-client-service:
        condition: service_started
      postgres:
        condition: service_healthy
    networks:
      - microservices-net

  # База данных PostgreSQL
  postgres:
    image: postgres:15-alpine
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_DB=restaurant_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=290404
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge

volumes:
  postgres_data:
  grafana_data:
  jenkins_home:
  rabbitmq_data: