global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "demo_app"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets:
          [
            "demo-rest:8080",  # Внутренний порт контейнера (не изменяется)
            "notification-service:8083",
            "audit-service:8082",
            "reservation-price-service:9091",  # Внутренний порт контейнера
            "price-client-service:8084",
          ]

